#!/bin/bash

# Execute all training commands generated by tune_for_option.py
# Skips already completed training runs (checks for model.pth and training_results.json)
#
# Usage:
#   1. First run: python crypto/scripts/tune_for_option.py ... (generates train_cmd.sh for each config)
#   2. Then run: bash run_all_training.sh (executes all training, skips completed)

echo "Starting batch training execution..."
total_runs=$(find results/hparam_tuning -name 'train_cmd.sh' 2>/dev/null | wc -l)
echo "Total runs found: $total_runs"

if [ "$total_runs" -eq 0 ]; then
    echo ""
    echo "❌ No training commands found!"
    echo ""
    echo "Please run tune_for_option.py first to generate configs:"
    echo "  python crypto/scripts/tune_for_option.py \\"
    echo "    --option-file <your-option-file> \\"
    echo "    --instrument <instrument-name>"
    echo ""
    exit 1
fi

echo

completed=0
skipped=0
failed=0

for dir in results/hparam_tuning/*/; do
    if [ -f "$dir/train_cmd.sh" ]; then
        run_name=$(basename "$dir")

        # Check if training already completed by looking for output files in train_* subdirs
        already_trained=false
        for train_subdir in "$dir"/train_*/; do
            if [ -d "$train_subdir" ] && [ -f "$train_subdir/model.pth" ] && [ -f "$train_subdir/training_results.json" ]; then
                already_trained=true
                break
            fi
        done

        if [ "$already_trained" = true ]; then
            echo "⏭  Skipping (already trained): $run_name"
            ((skipped++))
            continue
        fi

        echo "============================================================"
        echo "Running: $run_name"
        echo "Started: $(date)"
        echo "============================================================"

        # Execute from repo root (don't cd into directory)
        bash "$dir/train_cmd.sh"
        exit_code=$?

        if [ $exit_code -eq 0 ]; then
            echo "✓ Completed: $run_name"
            ((completed++))
        else
            echo "✗ Failed: $run_name (exit code: $exit_code)"
            ((failed++))
        fi
        echo
    fi
done

echo "============================================================"
echo "All training runs completed!"
echo "Summary:"
echo "  Completed: $completed"
echo "  Skipped: $skipped (already trained)"
echo "  Failed: $failed"
echo "  Total: $((completed + skipped + failed))"
echo "============================================================"
