name: Examples

env:
  PROJECT_NAME: pfhedge
  PYTHON_VERSION: '3.9'

on:
  workflow_dispatch:

jobs:

  examples:

    name: Examples

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install
      run: |
        pip install poetry
        poetry install
        poetry run pip install -r examples/requirements.txt

    - name: Run examples
      run: cd examples && find . -name '*.py' -exec poetry run python {} \;
